#!/bin/bash
# Source user profiles to get the correct python PATH
if [ -f ~/.bash_profile ]; then source ~/.bash_profile; fi
if [ -f ~/.zshrc ]; then source ~/.zshrc; fi
if [ -f ~/.bashrc ]; then source ~/.bashrc; fi

DIR=$(dirname "$0")
cd "$DIR/../../.."
export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
python3 launcher.py
